kibana.username=elastic
kibana.password=lYDy9=hjX_FUKqIYUeB0
kibana.url=http://data.adaxxpro.com:9200/kafka-*/_search
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
spring.main.web-application-type=none